package ir.coffevista.vista_native.features.shell

import androidx.compose.runtime.Composable

/** Feature UI supplied by the app composition root; Shell owns navigation only. */
data class ShellFeatureContent(
    val feedRoot: @Composable (
        onPostClick: (String) -> Unit,
        onAuthorClick: (String) -> Unit,
        onCreatePost: () -> Unit,
        onOpenStoryPlayer: (Int) -> Unit,
        onCreateStory: (android.net.Uri?) -> Unit,
        onNotifications: () -> Unit,
        onAppeal: (String) -> Unit,
        onHashtag: (String) -> Unit,
        onVideoClick: (String) -> Unit,
    ) -> Unit,
    val appeal: (@Composable (postId: String, onBack: () -> Unit) -> Unit),
    val hashtagPosts: (@Composable (hashtag: String, onBack: () -> Unit, onPostClick: (String) -> Unit, onAuthorClick: (String) -> Unit) -> Unit),
    val notifications: @Composable (
        onBack: () -> Unit,
        onPostClick: (String) -> Unit,
        onUserClick: (String) -> Unit,
        onChatClick: (String, String?) -> Unit,
        onSuggestionsClick: () -> Unit,
        onAppealClick: (String) -> Unit,
    ) -> Unit,
    val storyPlayer: (@Composable (initialUserIndex: Int, onClose: () -> Unit, onOpenProfile: (String) -> Unit, onOpenLink: (String) -> Unit) -> Unit),
    val storyCreate: (@Composable (initialUri: android.net.Uri?, onClose: () -> Unit, onStoryPublished: () -> Unit) -> Unit),
    val addPost: (@Composable (onBack: () -> Unit, onNavigateToTrimmer: (android.net.Uri) -> Unit, onPostCreated: () -> Unit) -> Unit),
    val videoTrimmer: (@Composable (videoUri: android.net.Uri, onBack: () -> Unit, onTrimComplete: (java.io.File) -> Unit) -> Unit),
    val reels: (@Composable (postId: String?, onBack: () -> Unit, onAuthorClick: (String) -> Unit, onCommentsClick: (String) -> Unit, onShareClick: (String) -> Unit) -> Unit)? = null,
    val searchRoot: @Composable (
        onOpenWorkspace: () -> Unit,
        onOpenQrScanner: () -> Unit,
    ) -> Unit,
    val searchWorkspace: @Composable (
        onUserClick: (String) -> Unit,
        onPostClick: (String) -> Unit,
        onHashtagClick: (String) -> Unit,
    ) -> Unit,
    val ownProfile: @Composable (
        onPostClick: (String) -> Unit,
        onSettingsClick: () -> Unit,
        onLogout: () -> Unit,
        onOpenFollowers: (userId: String, initialTab: Int) -> Unit,
        onOpenQrScanner: () -> Unit,
        onEditProfile: () -> Unit,
        onAddStory: () -> Unit,
        onReelClick: (String) -> Unit,
    ) -> Unit,
    val postDetail: @Composable (
        onBack: () -> Unit,
        onAuthorClick: (String) -> Unit,
        onHashtagClick: (String) -> Unit,
        onAppealClick: (String) -> Unit,
        onNavigateToStoryEditor: (android.net.Uri) -> Unit,
    ) -> Unit,
    val userProfile: @Composable (
        userId: String,
        onBack: () -> Unit,
        onSelfProfile: () -> Unit,
        onPostClick: (String) -> Unit,
        onOpenFollowers: (userId: String, initialTab: Int) -> Unit,
        onOpenChat: ((userId: String) -> Unit)?,
        onReelClick: (String) -> Unit,
    ) -> Unit,
    val followersFollowing: (@Composable (userId: String, initialTab: Int, onBack: () -> Unit, onOpenProfile: (String) -> Unit) -> Unit),
    val qrScanner: (@Composable (onBack: () -> Unit, onUserFound: (String) -> Unit) -> Unit),
    val settingsRoot: (@Composable (
        onBack: () -> Unit,
        onEditProfile: () -> Unit,
        onPremium: () -> Unit,
        onAccountDetails: () -> Unit,
        onPrivacySecurity: () -> Unit,
        onNotifications: () -> Unit,
        onAppearance: () -> Unit,
        onDataStorage: () -> Unit,
        onSavedPosts: () -> Unit,
        onChangePassword: () -> Unit,
        onVerificationRequest: () -> Unit,
        onTerms: () -> Unit,
        onAbout: () -> Unit,
        onLogout: () -> Unit,
    ) -> Unit),
    val editProfile: (@Composable (onBack: () -> Unit) -> Unit),
    val pricingPage: (@Composable (onBack: () -> Unit) -> Unit),
    val privacySecurity: (@Composable (onBack: () -> Unit, onBlockedUsers: () -> Unit, onActiveSessions: () -> Unit) -> Unit),
    val activeSessions: (@Composable (onBack: () -> Unit) -> Unit),
    val blockedUsers: (@Composable (onBack: () -> Unit) -> Unit),
    val notificationSettings: (@Composable (onBack: () -> Unit) -> Unit),
    val themeSettings: (@Composable (onBack: () -> Unit) -> Unit),
    val dataStorage: (@Composable (onBack: () -> Unit) -> Unit),
    val savedPosts: (@Composable (onBack: () -> Unit, onPostClick: (String) -> Unit) -> Unit),
    val changePassword: (@Composable (onBack: () -> Unit) -> Unit),
    val verificationRequest: (@Composable (onBack: () -> Unit) -> Unit),
    val termsConditions: (@Composable (onBack: () -> Unit) -> Unit),
    val aboutSettings: (@Composable (
        onBack: () -> Unit,
        onSlideshow: () -> Unit,
        onTerms: () -> Unit,
        onContactUs: () -> Unit,
        onPrivacyPolicy: () -> Unit,
        onFaq: () -> Unit,
    ) -> Unit),
    val aboutSlideshow: (@Composable (onClose: () -> Unit) -> Unit),
    val contactUs: (@Composable (
        onBack: () -> Unit,
        onOpenSupportConversation: (conversationId: String, title: String) -> Unit,
    ) -> Unit),
    val privacyPolicy: (@Composable (onBack: () -> Unit) -> Unit),
    val faqPage: (@Composable (onBack: () -> Unit) -> Unit),
    val servicesRoot: (@Composable (
        onNearby: () -> Unit,
        onGame: () -> Unit,
        onTopGroups: () -> Unit,
        onContacts: () -> Unit,
        onUserProfile: (String) -> Unit,
        onWeb: (String, String) -> Unit,
        onSectionRoute: (String) -> Unit,
    ) -> Unit),
    val servicesContacts: (@Composable (() -> Unit, (String) -> Unit) -> Unit),
    val servicesTopGroups: (@Composable (() -> Unit, (String) -> Unit) -> Unit),
    val servicesGameLaunch: (@Composable (() -> Unit, (String, String) -> Unit) -> Unit),
    val servicesNearby: (@Composable (
        onBack: () -> Unit,
        onOpenLikes: () -> Unit,
        onOpenProfile: (String, String) -> Unit,
        onOpenChat: (String, String, String, String) -> Unit,
    ) -> Unit),
    val servicesNearbyLikes: (@Composable (
        onBack: () -> Unit,
        onOpenChat: (String, String, String, String) -> Unit,
    ) -> Unit),
    val servicesWeb: (@Composable (String, String, () -> Unit) -> Unit),
    val chatRoot: (@Composable ((String, String) -> Unit, () -> Unit) -> Unit),
    val chatNewMessage: (@Composable (() -> Unit, (String, String) -> Unit) -> Unit),
    val chatDetail: (@Composable (String, String?, String, () -> Unit, (String) -> Unit) -> Unit),
    val chatBadgeCount: Int = 0,
)
